"""Release domain layer (business models and rules)."""

from __future__ import annotations

from ms.release.domain.candidate_models import (
    CANDIDATE_SCHEMA,
    CandidateArtifact,
    CandidateInputRepo,
    CandidateManifest,
)
from ms.release.domain.candidate_producers import (
    TRUSTED_CANDIDATE_PRODUCERS,
    TrustedCandidateProducer,
    resolve_trusted_candidate_producer,
)
from ms.release.domain.config import (
    APP_CANDIDATE_WORKFLOW,
    APP_DEFAULT_BRANCH,
    APP_LOCAL_DIR,
    APP_RELEASE_ENV,
    APP_RELEASE_REPO,
    APP_RELEASE_WORKFLOW,
    APP_REPO_SLUG,
    DIST_DEFAULT_BRANCH,
    DIST_LOCAL_DIR,
    DIST_NOTES_DIR,
    DIST_PUBLISH_WORKFLOW,
    DIST_REPO_SLUG,
    DIST_SPEC_DIR,
    MS_DEFAULT_BRANCH,
    MS_RELEASE_ALIGNMENT_WORKFLOW,
    MS_REPO_SLUG,
    RELEASE_REPOS,
)
from ms.release.domain.models import (
    AppReleasePlan,
    DistributionRelease,
    PinnedRepo,
    ReleaseBump,
    ReleaseChannel,
    ReleasePlan,
    ReleaseRepo,
    ReleaseTooling,
    RepoCommit,
)
from ms.release.domain.planner import ReleaseHistory, compute_history, suggest_tag, validate_tag
from ms.release.domain.semver import SemVer, format_beta_tag, parse_beta_tag, parse_stable_tag

__all__ = [
    "APP_CANDIDATE_WORKFLOW",
    "APP_DEFAULT_BRANCH",
    "APP_LOCAL_DIR",
    "APP_RELEASE_ENV",
    "APP_RELEASE_REPO",
    "APP_RELEASE_WORKFLOW",
    "APP_REPO_SLUG",
    "CANDIDATE_SCHEMA",
    "CandidateArtifact",
    "CandidateInputRepo",
    "CandidateManifest",
    "TRUSTED_CANDIDATE_PRODUCERS",
    "TrustedCandidateProducer",
    "DIST_DEFAULT_BRANCH",
    "DIST_LOCAL_DIR",
    "DIST_NOTES_DIR",
    "DIST_PUBLISH_WORKFLOW",
    "DIST_REPO_SLUG",
    "DIST_SPEC_DIR",
    "MS_DEFAULT_BRANCH",
    "MS_RELEASE_ALIGNMENT_WORKFLOW",
    "MS_REPO_SLUG",
    "RELEASE_REPOS",
    "AppReleasePlan",
    "DistributionRelease",
    "PinnedRepo",
    "ReleaseBump",
    "ReleaseChannel",
    "ReleaseHistory",
    "ReleasePlan",
    "ReleaseRepo",
    "ReleaseTooling",
    "RepoCommit",
    "SemVer",
    "compute_history",
    "format_beta_tag",
    "parse_beta_tag",
    "parse_stable_tag",
    "resolve_trusted_candidate_producer",
    "suggest_tag",
    "validate_tag",
]
